//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FosterSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FosterTable
    {
        public int Family_ID { get; set; }
        public string Foster_Family { get; set; }
        public string Type_of_Home { get; set; }
        public int Licensed_Beds { get; set; }
        public int Occupied_Beds { get; set; }
        public int Available_Beds { get; set; }
        public int Min_Age { get; set; }
        public int Max_Age { get; set; }
        public string Preferred_Gender { get; set; }
        public string Agency { get; set; }
        public string P_O_C { get; set; }
        public string Comments { get; set; }
    }
}
