//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FosterSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FosterTable
    {
        public int Family_ID { get; set; }
        public string Foster_Family_Name { get; set; }
        public string Type_of_Home { get; set; }
        public Nullable<int> Number_of_Licensed_Beds { get; set; }
        public Nullable<int> Number_of_Occupied_Beds { get; set; }
        public Nullable<int> Number_of_Available_Beds { get; set; }
        public Nullable<int> Minimum_Age { get; set; }
        public Nullable<int> Maximum_Age { get; set; }
        public string Gender_Preferance { get; set; }
        public string Managing_Agency { get; set; }
        public string Point_of_Contact { get; set; }
        public string Comments { get; set; }
    }
}
